version: '3.8'
services:
  dev-db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=nawy_assessment
      - DB_PORT=5432
    ports:
      - '5432:5432'

volumes:
  postgres:
